[OutputWriter] Fix the NUnit V3 output writer. (#25)
The old code does not work with very large files and results in an
exception similar to the following one when running the BCL test on
xamarin-macios

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at System.Xml.XmlEncodedRawTextWriter.WriteChars (System.Char[] buffer, System.Int32 index, System.Int32 count) [0x00017] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:616
  at System.Xml.XmlEncodedRawTextWriterIndent.WriteChars (System.Char[] buffer, System.Int32 index, System.Int32 count) [0x00007] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:1796
  at System.Xml.XmlWellFormedWriter.WriteChars (System.Char[] buffer, System.Int32 index, System.Int32 count) [0x00078] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlWellFormedWriter.cs:960
  at NUnit.Framework.Api.XmlNode.WriteTo (System.Xml.XmlWriter writer) [0x0005b] in /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/builds/downloads/ios-release-Darwin-2edccc52a78d90fea7bcbd37844164663e712397/ios-sources/external/nunit-lite/NUnitLite-1.0.0/src/framework/Api/XmlNode.cs:203
  at NUnit.Framework.Api.XmlNode.WriteTo (System.Xml.XmlWriter writer) [0x0008d] in /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/builds/downloads/ios-release-Darwin-2edccc52a78d90fea7bcbd37844164663e712397/ios-sources/external/nunit-lite/NUnitLite-1.0.0/src/framework/Api/XmlNode.cs:206
  at NUnit.Framework.Api.XmlNode.WriteTo (System.Xml.XmlWriter writer) [0x0008d] in /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/builds/downloads/ios-release-Darwin-2edccc52a78d90fea7bcbd37844164663e712397/ios-sources/external/nunit-lite/NUnitLite-1.0.0/src/framework/Api/XmlNode.cs:206
  at NUnit.Framework.Api.XmlNode.WriteTo (System.Xml.XmlWriter writer) [0x0008d] in /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/builds/downloads/ios-release-Darwin-2edccc52a78d90fea7bcbd37844164663e712397/ios-sources/external/nunit-lite/NUnitLite-1.0.0/src/framework/Api/XmlNode.cs:206
  at NUnit.Framework.Api.XmlNode.WriteTo (System.Xml.XmlWriter writer) [0x0008d] in /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/builds/downloads/ios-release-Darwin-2edccc52a78d90fea7bcbd37844164663e712397/ios-sources/external/nunit-lite/NUnitLite-1.0.0/src/framework/Api/XmlNode.cs:206
  at NUnit.Framework.Api.XmlNode.WriteTo (System.Xml.XmlWriter writer) [0x0008d] in /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/builds/downloads/ios-release-Darwin-2edccc52a78d90fea7bcbd37844164663e712397/ios-sources/external/nunit-lite/NUnitLite-1.0.0/src/framework/Api/XmlNode.cs:206
  at NUnitLite.Runner.NUnit3XmlOutputWriter.WriteXmlOutput (NUnit.Framework.Api.ITestResult result, System.Xml.XmlWriter xmlWriter) [0x0000e] in /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/builds/downloads/ios-release-Darwin-2edccc52a78d90fea7bcbd37844164663e712397/ios-sources/external/nunit-lite/NUnitLite-1.0.0/src/framework/Runner/OutputWriters/NUnit3XmlOutputWriter.cs:80
  at NUnitLite.Runner.NUnit3XmlOutputWriter.WriteResultFile (NUnit.Framework.Api.ITestResult result, System.IO.TextWriter writer) [0x00015] in /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/builds/downloads/ios-release-Darwin-2edccc52a78d90fea7bcbd37844164663e712397/ios-sources/external/nunit-lite/NUnitLite-1.0.0/src/framework/Runner/OutputWriters/NUnit3XmlOutputWriter.cs:66
  at MonoTouch.NUnit.NUnitOutputTextWriter.Close () [0x000bc] in /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/external/Touch.Unit/NUnitLite/TouchRunner/NUnitOutputTextWriter.cs:99
  at MonoTouch.NUnit.UI.BaseTouchRunner.CloseWriter () [0x0006c] in /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/external/Touch.Unit/NUnitLite/TouchRunner/TouchRunner.cs:366
```

The new implementation has no issues with large resultsi, as an example
it was used to generate: https://gist.github.com/mandel-macaque/57d61ce2251796682d7cda7fb9dca4f7